//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMvcDemo
{
    using System;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tProduct
    {
        [DisplayName("序號")]
        public int fId { get; set; }
        [DisplayName("產品名稱")]
        [Required(ErrorMessage = "產品名稱是必填欄位")]
        public string fName { get; set; }
        [DisplayName("成本")]
        public Nullable<decimal> fCost { get; set; }
        [DisplayName("在庫")]
        public string fQty { get; set; }
        [DisplayName("單價")]
        public Nullable<decimal> fPrice { get; set; }
        
    }
}
